version: '3.8'
services: # Define the services that make up your application
  app: # Name of the service
    build: . # Build the image from the Dockerfile in the current directory
    depends_on:
      - postgres
    ports: # Map port 8000 of the container to port 8000 on the host
      - "8000:8000" # <port on localhost>:<port in container>
    volumes:
      - ./:usr/src/app:ro # Mount the current directory to /usr/src/app in the container
      # env_file:
      #   - ./.env # Load environment variables from a .env file
    command: 
      - uvicorn main:app --host 0.0.0 --port 8000 --reload # Command to run the FastAPI application with auto-reload
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=admin
      - DATABASE_NAME=fastapi
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=9ee639a218fa963d483506621be126e81091ca9ac1a3af7ca9021626ae15cd4e
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30

  postgres: # Name of the PostgreSQL service
    image: postgres:latest # Use the latest PostgreSQL image from Docker Hub
    environment:
      - POSTGRES_USER=postgres # Set the PostgreSQL username
      - POSTGRES_PASSWORD=admin # Set the PostgreSQL password
      - POSTGRES_DB=fastapi # Set the PostgreSQL database name
    volumes:
      - postgres_db:/var/lib/postgresql/data # Persist PostgreSQL data in a named volume

volumes:
  postgres_db: # Define a named volume for PostgreSQL data persistence
    ports:
      - "5432:5432" # Map port 5432 of the container to port 5432 on the host