# name: Build and Deploy

# on: [push, pull_request]
# jobs:
#   build:
#     env:
#       DATABASE_HOSTNAME: localhost
#       DATABASE_PORT: 5432
#       DATABASE_PASSWORD: admin
#       DATABASE_NAME: fastapi
#       DATABASE_USERNAME: postgres
#       SECRET_KEY=9ee639a218fa963d483506621be126e81091ca9ac1a3af7ca9021626ae15cd4e
#       ALGORITHM=HS256
#       ACCESS_TOKEN_EXPIRE_MINUTES=30
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2
#     - name: Set up Python
#       uses: actions/setup-python@v2
#       with:
#         python-version: '3.9'
#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install -r requirements.txt
#     - name: Run tests
#       run: |
#         pytest tests/